# Generated by Django 3.0.3 on 2022-11-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user_iiiii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='iiiii',
        ),
    ]
