# Generated by Django 4.1 on 2022-11-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
