# Generated by Django 3.0.3 on 2022-11-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_user_iiiii'),
    ]

    operations = [
        migrations.CreateModel(
            name='testupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
