# Generated by Django 3.0.3 on 2022-11-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20221128_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
