# Generated by Django 4.1 on 2022-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_patient_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
