# Generated by Django 4.1 on 2022-11-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_patient_birthdate'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
