# Generated by Django 3.0.3 on 2022-11-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_patient_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='upload',
            field=models.ImageField(null=True, upload_to='images/%self.user.name'),
        ),
    ]
