# Generated by Django 4.1 on 2022-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
