# Generated by Django 3.0.3 on 2022-11-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20221128_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='doc',
            field=models.ImageField(null=True, upload_to='nurse_doc/%y/%m/%d'),
        ),
    ]
