# Generated by Django 3.0.3 on 2022-11-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_nurse_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='upload',
        ),
    ]
