# Generated by Django 3.0.3 on 2022-11-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_remove_patient_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
    ]
